/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.amf.eventmonitor.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StoreEvents service. Represents a row in the &quot;EventMonitor_StoreEvents&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.training.amf.eventmonitor.service.model.impl.StoreEventsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.training.amf.eventmonitor.service.model.impl.StoreEventsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreEvents
 * @see com.liferay.training.amf.eventmonitor.service.model.impl.StoreEventsImpl
 * @see com.liferay.training.amf.eventmonitor.service.model.impl.StoreEventsModelImpl
 * @generated
 */
@ProviderType
public interface StoreEventsModel extends BaseModel<StoreEvents> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a store events model instance should use the {@link StoreEvents} interface instead.
	 */

	/**
	 * Returns the primary key of this store events.
	 *
	 * @return the primary key of this store events
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store events.
	 *
	 * @param primaryKey the primary key of this store events
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this store events.
	 *
	 * @return the uuid of this store events
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this store events.
	 *
	 * @param uuid the uuid of this store events
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this store events.
	 *
	 * @return the foo ID of this store events
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this store events.
	 *
	 * @param fooId the foo ID of this store events
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this store events.
	 *
	 * @return the group ID of this store events
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this store events.
	 *
	 * @param groupId the group ID of this store events
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the logged of this store events.
	 *
	 * @return the logged of this store events
	 */
	public Date getLogged();

	/**
	 * Sets the logged of this store events.
	 *
	 * @param logged the logged of this store events
	 */
	public void setLogged(Date logged);

	/**
	 * Returns the user ID of this store events.
	 *
	 * @return the user ID of this store events
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this store events.
	 *
	 * @param userId the user ID of this store events
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this store events.
	 *
	 * @return the user uuid of this store events
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this store events.
	 *
	 * @param userUuid the user uuid of this store events
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this store events.
	 *
	 * @return the user name of this store events
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this store events.
	 *
	 * @param userName the user name of this store events
	 */
	public void setUserName(String userName);

	/**
	 * Returns the request ip of this store events.
	 *
	 * @return the request ip of this store events
	 */
	@AutoEscape
	public String getRequestIp();

	/**
	 * Sets the request ip of this store events.
	 *
	 * @param requestIp the request ip of this store events
	 */
	public void setRequestIp(String requestIp);

	/**
	 * Returns the event type of this store events.
	 *
	 * @return the event type of this store events
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this store events.
	 *
	 * @param eventType the event type of this store events
	 */
	public void setEventType(String eventType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StoreEvents storeEvents);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StoreEvents> toCacheModel();

	@Override
	public StoreEvents toEscapedModel();

	@Override
	public StoreEvents toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}